name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name:  Cache NPM dependencies
          with:
            key: "${os.runner}-node-${hashFiles(../package-lock.json)}"
            path: ../node_modules
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage: 
       name : code coverage
       runs-on: ubuntu-latest
       steps:
         - name: checkout repo
           uses: actions/checkout@v4

         - name : setup nodejs
           uses: actions/setup-node@v4
           with:
             node-version: 18
         - name: install dependencies
           run: npm install
         - name: code coverage
           run: npm run code-coverage
           continue-on-error: true
         - name: uploding code coverage
           uses: actions/upload-artifact@v4
           with:
               name: Code-Coverage-Result
               path: coverage
               retention-days: 5
           
